version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Login to npm
          command: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run:
          name: Publish to npm
          command: npm publish .
workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            tags: 
              only: /[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/